export default {
	profile_ru: 'личный кабинет',
	profile_uk: 'особистий кабінет',
	cart_ru: 'корзина',
	cart_uk: 'кошик',
	reviews_ru: 'отзывы',
	reviews_uk: 'відгуки',
	orders_ru: 'заказы',
	orders_uk: 'замовлення',
	checkout_ru: 'оформление заказа',
	checkout_uk: 'оформлення замовлення',
	delivery_payment_ru: 'доставка и оплата',
	delivery_payment_uk: 'доставка і оплата',
	contacts_ru: 'контакты',
	contacts_uk: 'контакти',
	about_us_ru: 'о магазине',
	about_us_uk: 'про магазин',
	privacy_policy_ru: 'политика конфиденциальности',
	privacy_policy_uk: 'політика конфіденційності',
	new_products_ru: 'новинки',
	new_products_uk: 'новинки',
};